### ISSUE TITLE
Network support cloud and dedi

### ISSUE THREAD

**Issue by stefandevo** [identw/hetzner-cloud-controller-manager#1]
About the note

_Note: Unlike the original controller, this controller does not support Hetzner cloud networks, because using them it is impossible to build a network between the cloud and dedicated servers_

https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch/

could this be possible then?

**Comment by identw** [comment]
@stefandevo 
Thanks. Apparently they added new functionality. I will check if it is possible to use this functionality in the controller.

**Comment by identw** [comment]
@stefandevo 
Hello. I researched the question. Unfortunately, this is not technically possible to implement, since there are restrictions in the settings of hetzner cloud routes.

For example:
hetzner cloud network: 10.240.0.0/12, subnet for cloud nodes: 10.240.0.0/24, subnet for connect vswitch (dedicated nodes): 10.240.1.0/24
Cluster Pod CIDR: 10.245.0.0/16
kube-master121-1 (cloud node, hel-dc2) - public IP: 95.216.201.207, private IP: 10.240.0.2, pod network: 10.245.0.0/24
kube-worker121-1 (cloud node, hel-dc2) - public IP: 95.216.209.218, private IP: 10.240.0.3,  pod network: 10.245.1.0/24
kube-worker121-2 (cloud node, hel-dc2) - public IP: 135.181.41.158, private IP: 10.240.0.4, pod network: 10.245.2.0/24
kube-worker121-10 (dedicated node, hel-dc4) public IP: 135.181.96.131, private IP: 10.240.1.2, pod network: 10.245.3.0/24
Vlan network on kube-worker121-10:
```
3: enp34s0.4002@enp34s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default qlen 1000
    link/ether 2c:f0:6d:05:d1:ae brd ff:ff:ff:ff:ff:ff
    inet 10.240.1.2/24 scope global enp34s0.4002
       valid_lft forever preferred_lft forever
    inet6 fe80::2ef0:5dff:fe0d:dcae/64 scope link 
       valid_lft forever preferred_lft forever
```
![image](https://user-images.githubusercontent.com/22338503/111874592-ce69e900-89b7-11eb-8ab8-288840d83f5c.png)
![image](https://user-images.githubusercontent.com/22338503/111874636-e7729a00-89b7-11eb-9686-6fe438633c11.png)


Of course, nodes are connected to each other on the same subnet (10.240.0.0/12). But this is not enough to organize pod-to-pod communication. Since for this you need to be able to create routes as for cloud nodes.
For example, for node kube-master121-1 has the following routes:
10.245.1.0/24 via 10.240.0.3 (cloud node kube-worker121-1) - Can be created via AP
10.245.2.0/24 via 10.240.0.4 (cloud node kube-worker121-2) - Can be created via AP
10.245.3.0/24 via 10.240.1.2 (dedicated node kube-worker121-10) - It is impossible to create such a route in any way
![image](https://user-images.githubusercontent.com/22338503/111875069-a67b8500-89b9-11eb-9b5e-9d85fdbe38ee.png)


But I can't create route for dedicated node:
![image](https://user-images.githubusercontent.com/22338503/111875090-c9a63480-89b9-11eb-8aa2-b349fadaa857.png)
Routes can only be created for cloud nodes:
![image](https://user-images.githubusercontent.com/22338503/111875100-dfb3f500-89b9-11eb-8fee-e2b4654d2d4e.png)

Thus, this cannot be achieved since it is impossible to create routes for a network of pods to dedicated servers.


In addition, you hardly want to connect cloud servers with dedicated via vswitch since latency is greatly degraded in comparison with the public network:
ping cloud (kube-master121-1) to dedicated (kube-worker121-10) via public ip:
```
$ ping 135.181.96.131
PING 135.181.96.131 (135.181.96.131) 56(84) bytes of data.
64 bytes from 135.181.96.131: icmp_seq=1 ttl=59 time=0.442 ms
64 bytes from 135.181.96.131: icmp_seq=2 ttl=59 time=0.372 ms
64 bytes from 135.181.96.131: icmp_seq=3 ttl=59 time=0.460 ms
64 bytes from 135.181.96.131: icmp_seq=4 ttl=59 time=0.539 ms
```
ping cloud (kube-master121-1) to dedicated (kube-worker121-10) via vswitch:
```
$ ping 10.240.1.2
PING 10.240.1.2 (10.240.1.2) 56(84) bytes of data.
64 bytes from 10.240.1.2: icmp_seq=1 ttl=63 time=47.4 ms
64 bytes from 10.240.1.2: icmp_seq=2 ttl=63 time=47.0 ms
64 bytes from 10.240.1.2: icmp_seq=3 ttl=63 time=46.9 ms
64 bytes from 10.240.1.2: icmp_seq=4 ttl=63 time=46.9 ms
```
~0.5ms via public network vs 46.5ms  via private network =(.
